use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;

use tempfile::tempdir;

#[test]
fn commit_runs_agent_opens_editor_and_commits_non_empty_message() {
    let temp = tempdir().expect("tempdir should be created");
    let root = temp.path();
    let bin_dir = root.join("bin");
    fs::create_dir(&bin_dir).expect("bin dir should be created");

    write_executable(
        &bin_dir.join("git"),
        r#"#!/bin/sh
set -eu
log_dir=$(dirname "$0")/../logs
mkdir -p "$log_dir"
printf '%s\n' "$*" >> "$log_dir/git.log"
if [ "$1" = "diff" ] && [ "$2" = "--cached" ]; then
  if [ "${3:-}" = "--name-only" ]; then
    printf 'src/main.rs\n'
    exit 0
  fi
  if [ "${3:-}" = "--numstat" ]; then
    printf '1\t0\tsrc/main.rs\n'
    exit 0
  fi
  printf 'diff --git a/src/main.rs b/src/main.rs\n+new line\n'
  exit 0
fi
if [ "$1" = "show" ] && [ "$2" = ":src/main.rs" ]; then
  printf 'fn main() {\n    println!("hello");\n}\n'
  exit 0
fi
if [ "$1" = "commit" ] && [ "$2" = "--file" ]; then
  cp "$3" "$log_dir/raw-commit-message.txt"
  awk '
    /^#/ { next }
    { lines[++count] = $0 }
    END {
      while (count > 0 && lines[count] == "") {
        count--
      }
      for (i = 1; i <= count; i++) {
        print lines[i]
      }
    }
  ' "$3" > "$log_dir/committed-message.txt"
  exit 0
fi
echo "unexpected git invocation: $*" >&2
exit 1
"#,
    );

    write_executable(
        &bin_dir.join("codex"),
        r#"#!/bin/sh
set -eu
log_dir=$(dirname "$0")/../logs
mkdir -p "$log_dir"
printf '%s\n' "$*" > "$log_dir/agent-args.txt"
cat > "$log_dir/agent-prompt.txt"
output_file=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "-o" ]; then
    output_file="$arg"
    break
  fi
  prev="$arg"
done
printf 'feat: add rust commit workflow\n\nGenerated by fake codex.\n' > "$output_file"
printf '{"type":"item.completed","item":{"type":"agent_message","text":"feat: add rust commit workflow\n\nGenerated by fake codex."}}\n'
"#,
    );

    write_executable(
        &bin_dir.join("editor"),
        r#"#!/bin/sh
set -eu
log_dir=$(dirname "$0")/../logs
mkdir -p "$log_dir"
cp "$1" "$log_dir/editor-input.txt"
printf 'feat: finalize commit flow\n\nEdited in fake editor.\n' > "$1"
"#,
    );

    let output = run_agents(
        root,
        &bin_dir,
        &[
            "commit",
            "--cli",
            "codex",
            "--root",
            root.to_str().expect("root path should be utf-8"),
        ],
    );

    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert!(String::from_utf8_lossy(&output.stdout).trim().is_empty());

    let prompt = fs::read_to_string(root.join("logs/agent-prompt.txt")).expect("agent prompt should exist");
    assert!(prompt.contains("Return only the commit message text"));
    assert!(prompt.contains("diff --git a/src/main.rs b/src/main.rs"));
    assert!(prompt.contains("Do not run tools or inspect the repository"));
    assert!(prompt.contains("Staged file contents:"));
    assert!(prompt.contains("File: src/main.rs"));
    assert!(prompt.contains("println!(\"hello\");"));
    let agent_args = fs::read_to_string(root.join("logs/agent-args.txt")).expect("agent args should exist");
    assert!(agent_args.contains("exec --json --skip-git-repo-check"));
    assert!(agent_args.contains("--sandbox read-only"));
    assert!(agent_args.contains("-o"));

    let committed_message =
        fs::read_to_string(root.join("logs/committed-message.txt")).expect("commit message should be captured");
    assert_eq!(committed_message, "feat: finalize commit flow\n\nEdited in fake editor.\n");
    let editor_input =
        fs::read_to_string(root.join("logs/editor-input.txt")).expect("editor input should be captured");
    assert!(editor_input.starts_with("feat: add rust commit workflow\n\nGenerated by fake codex.\n\n#\n"));
    assert!(editor_input.contains("# Changes to be committed:\n"));
    assert!(editor_input.contains("# src/main.rs | 1 lines changed (+1 -0)\n"));
    let raw_message =
        fs::read_to_string(root.join("logs/raw-commit-message.txt")).expect("raw commit message should be captured");
    assert_eq!(raw_message, "feat: finalize commit flow\n\nEdited in fake editor.\n");

    let git_log = fs::read_to_string(root.join("logs/git.log")).expect("git log should exist");
    assert!(git_log.contains("diff --cached"));
    assert!(git_log.contains("diff --cached --numstat --diff-filter=ACMRD"));
    assert!(git_log.contains("commit --file"));
}

#[test]
fn commit_aborts_when_editor_clears_message() {
    let temp = tempdir().expect("tempdir should be created");
    let root = temp.path();
    let bin_dir = root.join("bin");
    fs::create_dir(&bin_dir).expect("bin dir should be created");

    write_executable(
        &bin_dir.join("git"),
        r#"#!/bin/sh
set -eu
log_dir=$(dirname "$0")/../logs
mkdir -p "$log_dir"
printf '%s\n' "$*" >> "$log_dir/git.log"
if [ "$1" = "diff" ] && [ "$2" = "--cached" ]; then
  if [ "${3:-}" = "--name-only" ]; then
    printf 'README.md\n'
    exit 0
  fi
  if [ "${3:-}" = "--numstat" ]; then
    printf '1\t0\tREADME.md\n'
    exit 0
  fi
  printf 'diff --git a/README.md b/README.md\n+docs\n'
  exit 0
fi
if [ "$1" = "show" ] && [ "$2" = ":README.md" ]; then
  printf '# Agents\n'
  exit 0
fi
if [ "$1" = "commit" ]; then
  echo "git commit should not be called" >&2
  exit 1
fi
echo "unexpected git invocation: $*" >&2
exit 1
"#,
    );

    write_executable(
        &bin_dir.join("qwen"),
        r#"#!/bin/sh
set -eu
cat > /dev/null
printf '{"type":"result","result":"docs: update README"}\n'
"#,
    );

    write_executable(
        &bin_dir.join("editor"),
        r#"#!/bin/sh
set -eu
: > "$1"
"#,
    );

    let output = run_agents(
        root,
        &bin_dir,
        &[
            "commit",
            "--cli",
            "qwen",
            "--root",
            root.to_str().expect("root path should be utf-8"),
        ],
    );

    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));
    assert_eq!(
        String::from_utf8_lossy(&output.stdout).trim(),
        "message empty, aborting commit"
    );

    let git_log = fs::read_to_string(root.join("logs/git.log")).expect("git log should exist");
    assert!(git_log.contains("diff --cached"));
    assert!(!git_log.contains("commit --file"));
}

#[test]
fn commit_passes_real_staged_diff_and_file_context_to_agent() {
    let temp = tempdir().expect("tempdir should be created");
    let root = temp.path();
    let bin_dir = root.join("bin");
    let logs_dir = root.join("logs");
    let src_dir = root.join("src");

    fs::create_dir(&bin_dir).expect("bin dir should be created");
    fs::create_dir(&logs_dir).expect("logs dir should be created");
    fs::create_dir(&src_dir).expect("src dir should be created");

    run_in_repo(root, &["git", "init"]);
    run_in_repo(root, &["git", "config", "user.name", "Test User"]);
    run_in_repo(root, &["git", "config", "user.email", "test@example.com"]);

    let file_path = src_dir.join("main.rs");
    fs::write(&file_path, "fn main() {\n    println!(\"before\");\n}\n")
        .expect("initial file should be written");
    run_in_repo(root, &["git", "add", "src/main.rs"]);
    run_in_repo(root, &["git", "commit", "-m", "initial"]);

    fs::write(
        &file_path,
        "fn main() {\n    println!(\"after\");\n    println!(\"context\");\n}\n",
    )
    .expect("updated file should be written");
    run_in_repo(root, &["git", "add", "src/main.rs"]);

    write_executable(
        &bin_dir.join("codex"),
        r#"#!/bin/sh
set -eu
log_dir=$(dirname "$0")/../logs
mkdir -p "$log_dir"
cat > "$log_dir/agent-prompt.txt"
output_file=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "-o" ]; then
    output_file="$arg"
    break
  fi
  prev="$arg"
done
printf 'feat: real repo test\n' > "$output_file"
"#,
    );

    write_executable(
        &bin_dir.join("editor"),
        r#"#!/bin/sh
set -eu
printf 'feat: real repo test\n' > "$1"
"#,
    );

    let output = run_agents(
        root,
        &bin_dir,
        &[
            "commit",
            "--cli",
            "codex",
            "--root",
            root.to_str().expect("root path should be utf-8"),
        ],
    );

    assert!(output.status.success(), "stderr: {}", String::from_utf8_lossy(&output.stderr));

    let prompt = fs::read_to_string(logs_dir.join("agent-prompt.txt")).expect("agent prompt should exist");
    assert!(prompt.contains("Staged diff:"));
    assert!(prompt.contains("diff --git a/src/main.rs b/src/main.rs"));
    assert!(prompt.contains("-    println!(\"before\");"));
    assert!(prompt.contains("+    println!(\"after\");"));
    assert!(prompt.contains("+    println!(\"context\");"));
    assert!(prompt.contains("Staged file contents:"));
    assert!(prompt.contains("File: src/main.rs"));
    assert!(prompt.contains("println!(\"after\");"));
    assert!(prompt.contains("println!(\"context\");"));
    assert!(!prompt.contains("println!(\"before\");\n}\n```"));
}

#[test]
fn commit_times_out_for_unresponsive_codex_agent() {
    let temp = tempdir().expect("tempdir should be created");
    let root = temp.path();
    let bin_dir = root.join("bin");
    let src_dir = root.join("src");

    fs::create_dir(&bin_dir).expect("bin dir should be created");
    fs::create_dir(&src_dir).expect("src dir should be created");

    run_in_repo(root, &["git", "init"]);
    run_in_repo(root, &["git", "config", "user.name", "Test User"]);
    run_in_repo(root, &["git", "config", "user.email", "test@example.com"]);

    let file_path = src_dir.join("main.rs");
    fs::write(&file_path, "fn main() {\n    println!(\"before\");\n}\n")
        .expect("initial file should be written");
    run_in_repo(root, &["git", "add", "src/main.rs"]);
    run_in_repo(root, &["git", "commit", "-m", "initial"]);

    fs::write(&file_path, "fn main() {\n    println!(\"after\");\n}\n")
        .expect("updated file should be written");
    run_in_repo(root, &["git", "add", "src/main.rs"]);

    write_executable(
        &bin_dir.join("codex"),
        r#"#!/bin/sh
set -eu
cat > /dev/null
sleep 5
"#,
    );

    write_executable(
        &bin_dir.join("editor"),
        r#"#!/bin/sh
set -eu
printf 'should not run\n' > "$1"
"#,
    );

    let output = run_agents_with_env(
        root,
        &bin_dir,
        &[
            "commit",
            "--cli",
            "codex",
            "--root",
            root.to_str().expect("root path should be utf-8"),
        ],
        &[("AGENTS_TIMEOUT_SECS", "1")],
    );

    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("asking codex for a commit message (1s timeout)..."));
    assert!(stderr.contains("codex timed out after 1s"));
    assert!(!stderr.contains("opening $EDITOR..."));
}

#[test]
fn commit_fails_when_nothing_is_staged() {
    let temp = tempdir().expect("tempdir should be created");
    let root = temp.path();
    let bin_dir = root.join("bin");
    let logs_dir = root.join("logs");
    let src_dir = root.join("src");

    fs::create_dir(&bin_dir).expect("bin dir should be created");
    fs::create_dir(&logs_dir).expect("logs dir should be created");
    fs::create_dir(&src_dir).expect("src dir should be created");

    run_in_repo(root, &["git", "init"]);
    run_in_repo(root, &["git", "config", "user.name", "Test User"]);
    run_in_repo(root, &["git", "config", "user.email", "test@example.com"]);

    let file_path = src_dir.join("main.rs");
    fs::write(&file_path, "fn main() {\n    println!(\"committed\");\n}\n")
        .expect("initial file should be written");
    run_in_repo(root, &["git", "add", "src/main.rs"]);
    run_in_repo(root, &["git", "commit", "-m", "initial"]);

    write_executable(
        &bin_dir.join("codex"),
        r#"#!/bin/sh
set -eu
log_dir=$(dirname "$0")/../logs
mkdir -p "$log_dir"
printf 'called\n' > "$log_dir/codex-called.txt"
exit 1
"#,
    );

    write_executable(
        &bin_dir.join("editor"),
        r#"#!/bin/sh
set -eu
log_dir=$(dirname "$0")/../logs
mkdir -p "$log_dir"
printf 'called\n' > "$log_dir/editor-called.txt"
exit 1
"#,
    );

    let output = run_agents(
        root,
        &bin_dir,
        &[
            "commit",
            "--cli",
            "codex",
            "--root",
            root.to_str().expect("root path should be utf-8"),
        ],
    );

    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("collecting staged diff..."));
    assert!(stderr.contains("nothing staged"));
    assert!(!stderr.contains("asking codex for a commit message"));
    assert!(!logs_dir.join("codex-called.txt").exists());
    assert!(!logs_dir.join("editor-called.txt").exists());
}

fn run_agents(root: &Path, bin_dir: &Path, args: &[&str]) -> std::process::Output {
    run_agents_with_env(root, bin_dir, args, &[])
}

fn run_agents_with_env(
    root: &Path,
    bin_dir: &Path,
    args: &[&str],
    extra_env: &[(&str, &str)],
) -> std::process::Output {
    let path = format!(
        "{}:{}",
        bin_dir.display(),
        std::env::var("PATH").expect("PATH should be set")
    );

    let mut command = Command::new(env!("CARGO_BIN_EXE_agents"));
    command
        .args(args)
        .current_dir(root)
        .env("PATH", path)
        .env("EDITOR", bin_dir.join("editor"));

    if bin_dir.join("codex").is_file() {
        command.env("AGENTS_CODEX_BIN", bin_dir.join("codex"));
    }

    for (key, value) in extra_env {
        command.env(key, value);
    }

    command.output().expect("agents binary should run")
}

fn run_in_repo(root: &Path, args: &[&str]) {
    let status = Command::new(args[0])
        .args(&args[1..])
        .current_dir(root)
        .status()
        .expect("command should run");
    assert!(status.success(), "command failed: {}", args.join(" "));
}

fn write_executable(path: &PathBuf, contents: &str) {
    fs::write(path, contents).expect("script should be written");
    let mut permissions = fs::metadata(path)
        .expect("script metadata should exist")
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(path, permissions).expect("script should be executable");
}
